version: '2'

networks:
  wvc-backend:

volumes:
  db_data:
  portainer_data:

services:
  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - wvc-backend
    image: postgres:13.2
    container_name: wvc-db

  wvc:
    depends_on:
      - db
    ports:
      - "6080:6080"
    volumes:
      - /srv/webvirtcloud
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.wvc.entrypoints: web
      traefik.http.routers.wvc.rule: Host(`${WVC_HOST}`)
      traefik.http.services.wvc.loadbalancer.server.port: '8000'
    networks:
      - wvc-backend
    image: kenlee/webvirtcloud-docker:latest
    container_name: wvc

  wvc-assets:
    depends_on:
      - wvc
    volumes_from:
      - wvc:ro
    labels:
      traefik.enable: 'true'
      traefik.http.routers.wvc-assets.entrypoints: web
      traefik.http.routers.wvc-assets.rule: Host(`${WVC_HOST}`) && PathPrefix(`/static/`)
    command:
      - "caddy"
      - "file-server"
      - "--root"
      - "/srv/webvirtcloud"
      - "/static/*"
    image: caddy:2-alpine

  portainer:
    depends_on:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      traefik.enable: 'true'
      traefik.http.routers.portainer.entrypoints: web
      traefik.http.routers.portainer.rule: Host(`${PORTAINER_HOST}`)
      traefik.http.services.portainer.loadbalancer.server.port: '9000'
    image: portainer/portainer-ce
    container_name: portainer

  traefik:
    image: traefik:2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
