version: '2'

networks:
  tailscaled:
    external:
      name: tailscale-vpn0

services:
  traefik:
    command:
      - "--providers.docker.network=tailscale-vpn0"
    networks:
      - tailscaled

  wvc:
    networks:
      - tailscaled

  wvc:
    networks:
      - tailscaled

  portainer:
    networks:
      - tailscaled
