version: '2'

networks:
  tailscaled:
    external:
      name: tailscale-vpn0

services:
  traefik:
    networks:
      - tailscaled

  wvc:
    networks:
      - tailscaled

  wvc-assets:
    networks:
      - tailscaled

  portainer:
    networks:
      - tailscaled
